### ISSUE TITLE
"list series" doesn't show series names

### ISSUE THREAD

**Issue by Dieterbe** [FGRibreau/influxdb-cli#8]
```
influxdb-cli <<< 'list series' | less
graphite> Connecting to <censored> ...
graphite> ✔ ready
graphite> ┌──────┬─────────────────┐
│ time │ sequence_number │
└──────┴─────────────────┘
Query took  626 ms
┌──────┬─────────────────┐
│ time │ sequence_number │
└──────┴─────────────────┘
Query took  626 ms
┌──────┬─────────────────┐
│ time │ sequence_number │
└──────┴─────────────────┘
Query took  626 ms
```

it's only showing column names, not the series names?

**Comment by jvshahid** [comment]
This is actually a bug (or feature) in the way list series work as of version 0.5.1 there's a story to change this behavior https://github.com/influxdb/influxdb/issues/358 Currently `list series` will return an array of empty series with the name field set to the series name.

That said, the cli should probably display the name of the time series, since the query language allows querying more than one query at the same time using regex. Without the series name it will be hard to make sense of the data.

**Comment by Dieterbe** [comment]
hi @FGRibreau any plans on leveraging the change in influxdb/influxdb#358 ?

**Comment by FGRibreau** [comment]
Hello @Dieterbe, currently no but I will happily merge a pull-request for this !

**Comment by jvshahid** [comment]
I don't think there's anything to be done for influxdb/influxdb#358. Once this change makes into master, series names will show up as rows in the result set. Isn't that right @FGRibreau ?

**Comment by FGRibreau** [comment]
Now that I took the time to understand the issue I think @jvshahid is right indeed. /cc @Dieterbe

**Comment by Dieterbe** [comment]
sorry i got confused.  I thought the needed patch had already been merged in influx.

**Comment by tamsky** [comment]
`SELECT * from /.*/ LIMIT 1` is influxdb's suggested alternate query for `list series`.

In infludb-cli, this SELECT query has the same behavior, and does not display the series name.

It would be great if one or both of these queries could be made to work before influxdb/influxdb#358.

**Comment by Dieterbe** [comment]
`select .. limit 1` is probably much more expensive than `list series` though, cause it has to look at the data for every series

**Comment by codyhanson** [comment]
I believe we can close this issue, due to #13 (by @macbre) being merged.

**Comment by FGRibreau** [comment]
@codyhanson indeed!
